// Generated by CoffeeScript 1.4.0
(function() {
  var Medal, Medals;

  Medals = (function() {

    function Medals(list) {
      var _this = this;
      if (list.length === 3) {
        list.forEach(function(el) {
          return new Medal(el);
        });
      }
    }

    return Medals;

  })();

  Medal = (function() {

    function Medal(el) {
      var li;
      li = '<span class="int">' + el.int + '</span>';
      if (el.dec != null) {
        li += '<span class="dec">' + el.dec + '</span>';
      }
      li += '<span class="leyend">' + el.leyend + '</span>';
      console.log(li);
      switch (el.noteType) {
        case "instances":
          console.log(li);
          $('.instances .notesite .percent').append(li);
          break;
        case "disk":
          $('.disk .notesite .percent').append(li);
          break;
        case "memory":
          $('.memory .notesite .percent').append(li);
      }
    }

    return Medal;

  })();

  $(function() {
    var json, toPrint;
    json = {
      "nodeType": "notes",
      "notes": [
        {
          "noteType": "instances",
          "int": "16",
          "dec": null,
          "leyend": "Instancias"
        }, {
          "noteType": "disk",
          "int": "800",
          "dec": null,
          "leyend": "GB de Disco"
        }, {
          "noteType": "memory",
          "int": "180",
          "dec": null,
          "leyend": "GB de Memoria"
        }
      ]
    };
    return toPrint = new Medals(json.notes);
  });

}).call(this);
