// Generated by CoffeeScript 1.4.0
(function() {
  var Clouds;

  Clouds = (function() {

    Clouds.objects = [];

    Clouds.layers = [];

    Clouds.worldXAngle = 0;

    Clouds.worldYAngle = 0;

    Clouds.world = document.getElementById('world');

    Clouds.d = 0;

    Clouds.p = 400;

    function Clouds() {
      this.viewport = document.getElementById('viewport');
      viewport.style.webkitPerspective = Clouds.p;
      viewport.style.MozPerspective = Clouds.p;
      viewport.style.oPerspective = Clouds.p;
      this.generate();
      window.addEventListener('mousemove', function(e) {
        var d;
        Clouds.worldYAngle = -(.5 - (e.clientX / window.innerWidth)) * 180;
        Clouds.worldXAngle = (.5 - (e.clientY / window.innerHeight)) * 180;
        d = 0;
        return Clouds.updateView();
      });
      window.addEventListener('mousewheel', this.onContainerMouseWheel);
      window.addEventListener('DOMMouseScroll', this.onContainerMouseWheel);
    }

    Clouds.prototype.update = function() {
      var j, layer, t, _i, _ref;
      for (j = _i = 0, _ref = Clouds.layers.length; 0 <= _ref ? _i < _ref : _i > _ref; j = 0 <= _ref ? ++_i : --_i) {
        layer = Clouds.layers[j];
        layer.data.a += layer.data.speed;
        t = 'translateX( ' + layer.data.x + 'px ) translateY( ' + layer.data.y + 'px ) translateZ( ' + layer.data.z + 'px ) rotateY( ' + (-Clouds.worldYAngle) + 'deg ) rotateX( ' + (-Clouds.worldXAngle) + 'deg ) rotateZ( ' + layer.data.a + 'deg ) scale( ' + layer.data.s + ')';
        layer.style.webkitTransform = t;
        layer.style.MozTransform = t;
        layer.style.oTransform = t;
      }
      return requestAnimationFrame(this.update());
    };

    Clouds.updateView = function() {
      var t, world;
      world = document.getElementById('world');
      t = 'translateZ( ' + this.d + 'px ) \ rotateX( ' + this.worldXAngle + 'deg) \ rotateY( ' + this.worldYAngle + 'deg)';
      world.style.transform = t;
      world.style.webkitTransform = t;
      world.style.MozTransform = t;
      return world.style.oTransform = t;
    };

    Clouds.prototype.onContainerMouseWheel = function(event) {
      var d, _ref;
      event = event != null ? event : {
        event: window.event
      };
      d = d - ((_ref = event.detail) != null ? _ref : event.detail * -{
        5: event.wheelDelta / 8
      });
      return this.updateView();
    };

    Clouds.prototype.generate = function() {
      if (world.hasChildNodes()) {
        while (world.childNodes.length >= 1) {
          world.removeChild(world.firstChild);
        }
      }
      return Clouds.objects.push(this.createCloud());
    };

    Clouds.prototype.createCloud = function() {
      var a, cloud, div, j, r, s, src, t, x, y, z, _i, _ref;
      div = document.createElement('div');
      div.className += 'cloudBase';
      x = 256 - (Math.random() * 512);
      y = 256 - (Math.random() * 512);
      z = 256 - (Math.random() * 512);
      t = 'translateX( ' + x + 'px ) translateY( ' + y + 'px ) translateZ( ' + z + 'px )';
      div.style.webkitTransform = t;
      div.style.MozTransform = t;
      div.style.oTransform = t;
      world.appendChild(div);
      for (j = _i = 0, _ref = 5 + Math.round(Math.random() * 10); 0 <= _ref ? _i < _ref : _i > _ref; j = 0 <= _ref ? ++_i : --_i) {
        cloud = document.createElement('img');
        cloud.style.opacity = 0.8;
        r = Math.random();
        src = 'http://www.clicktorelease.com/blog/css3dclouds/cloud.png';
        cloud.addEventListener('load', function() {
          return cloud.style.opacity = .8;
        });
        cloud.setAttribute('src', src);
        cloud.className = 'cloudLayer';
        x = 256 - (Math.random() * 512);
        y = 256 - (Math.random() * 512);
        z = 100 - (Math.random() * 200);
        a = Math.random() * 360;
        s = .25 + Math.random();
        x *= .2;
        y *= .2;
        cloud.data = {
          x: x,
          y: y,
          z: z,
          a: a,
          s: s,
          speed: .1 * Math.random()
        };
        t = 'translateX( ' + x + 'px ) translateY( ' + y + 'px ) translateZ( ' + z + 'px ) rotateZ( ' + a + 'deg ) scale( ' + s + ' )';
        cloud.style.webkitTransform = t;
        cloud.style.MozTransform = t;
        cloud.style.oTransform = t;
        div.appendChild(cloud);
        Clouds.layers.push(cloud);
      }
      return div;
    };

    return Clouds;

  })();

  $(function() {
    var cloud;
    cloud = new Clouds();
    return cloud.update();
  });

}).call(this);
